
class TestDataEmptyArray(object):
    
    @staticmethod
    def get_array():
        # complete this function
        s=[]
        return  s

class TestDataUniqueValues(object):

    @staticmethod
    def get_array():
        # complete this function
        s=[1,2]
        return s

    @staticmethod
    def get_expected_result():
        # complete this function
        return 0

class TestDataExactlyTwoDifferentMinimums(object):

    @staticmethod
    def get_array():
        # complete this function
        s=[1,2,5,1]
        return s

    @staticmethod
    def get_expected_result():
        # complete this function
        return 0

